export const languageMap = {
  en: "en",
  "zh-cn": "zh-CN",
  "zh-tw": "zh-TW",
  fr: "fr-FR",
  de: "de-DE",
  it: "it-IT",
  es: "es-ES",
  ja: "ja-JA",
  ko: "ko-KO",
  ru: "ru-RU",
  "pt-br": "pt-BR",
  tr: "tr-TR",
  pl: "pl-PL",
  cs: "cs-CS",
};
